apiVersion: projectcalico.org/v3
kind: NetworkSet
metadata:
  name: domain-perdu-com
  labels:
    role: db
spec:
  #nets:
  #- 198.51.100.0/28
  #- 203.0.113.0/24
  allowedEgressDomains:
  - perdu.com
  - "*.perdu.com"

